const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  const page=await browser.newPage({viewport:{width:1365,height:960}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const dir=path.join(__dirname,'../.impeccable/review');fs.mkdirSync(dir,{recursive:true});
  await page.goto('http://127.0.0.1:8765/',{waitUntil:'networkidle'});
  await page.waitForFunction(()=>document.getElementById('research-count').textContent.includes('68,521'));
  const total=await page.locator('#total-count').textContent();
  console.log(total);
  assert.match(total,/1,190/);
  await page.locator('[data-region="city"]').click();
  assert.equal(await page.locator('#region-count').textContent(),'214店');
  await page.locator('#search').fill('大阪市此花区');await page.waitForTimeout(220);
  assert.ok(Number((await page.locator('#region-count').textContent()).replace(/\D/g,''))>=5);
  await page.locator('#search').fill('');await page.waitForTimeout(220);
  await page.locator('[data-region="all"]').click();
  await page.locator('#municipality').selectOption('箕面市');
  assert.ok(Number((await page.locator('#region-count').textContent()).replace(/\D/g,''))>=98);
  await page.locator('#search').fill('喫茶るうぷ');await page.waitForTimeout(220);
  await page.locator('#search').fill('丸美');await page.waitForTimeout(220);
  assert.equal(await page.locator('#items .item').count(),1);
  assert.match(await page.locator('#items').textContent(),/2024年/);
  assert.match(await page.locator('#items').textContent(),/2026-10-03/);
  await page.locator('#search').fill('');await page.waitForTimeout(220);
  await page.locator('#municipality').selectOption('all');
  assert.equal(await page.locator('#items .item').count(),50);
  const first=await page.locator('#items .name').first().textContent();
  await page.locator('#next').click();assert.notEqual(await page.locator('#items .name').first().textContent(),first);
  await page.locator('#previous').click();
  await page.locator('#rank-filter').selectOption('S');assert.equal(await page.locator('#items .item').count(),4);
  await page.locator('#rank-filter').selectOption('all');
  await page.locator('#search').fill('ありえない検索XYZ');await page.waitForTimeout(220);assert.equal(await page.locator('#items .item').count(),0);
  await page.locator('#clear-filters').click();
  await page.locator('[data-region="south"]').click();await page.locator('#municipality').selectOption('千早赤阪村');
  assert.equal(await page.locator('#items .item').count(),3);
  await page.screenshot({path:path.join(dir,'desktop.png'),fullPage:true});
  await page.locator('[data-region="all"]').click();
  await page.locator('[data-view="coverage"]').click();assert.equal(await page.locator('.coverage-row').count(),43);
  assert.equal(await page.locator('#rank-label').isVisible(),false);
  await page.locator('[data-city-open="能勢町"]').click();assert.equal(await page.locator('#municipality').inputValue(),'能勢町');
  await page.locator('[data-view="registry"]').click();await page.waitForFunction(()=>document.getElementById('region-count').textContent==='0件');
  assert.match(await page.locator('#items').textContent(),/店がない/);
  await page.locator('[data-region="all"]').click();await page.waitForFunction(()=>document.getElementById('region-count').textContent==='68,521件');
  assert.equal(await page.locator('#items .item').count(),50);
  const pages=await page.locator('#page-number option').count();await page.locator('#page-number').selectOption(String(pages));
  assert.equal(await page.locator('#items .item').count(),21);assert.equal(await page.locator('#next').isDisabled(),true);
  await page.locator('#municipality').selectOption('枚方市');await page.waitForFunction(()=>document.getElementById('region-count').textContent==='2,248件');
  await page.locator('[data-view="leads"]').click();await page.locator('[data-region="south"]').click();await page.locator('#municipality').selectOption('千早赤阪村');
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:path.join(dir,'mobile.png'),fullPage:true});
  await page.locator('[data-region="all"]').click();await page.evaluate(()=>window.scrollTo(0,0));
  await page.locator('#filter-toggle').click();assert.equal(await page.locator('#search').isVisible(),true);
  await page.locator('#filter-toggle').click();assert.equal(await page.locator('#search').isVisible(),false);
  assert.ok((await page.locator('#items .name').first().boundingBox()).y<750,'First candidate should be visible on mobile');
  await page.screenshot({path:path.join(dir,'mobile-default.png'),fullPage:false});
  const desktop=await browser.newPage({viewport:{width:1365,height:960}});
  await desktop.goto('http://127.0.0.1:8765/',{waitUntil:'networkidle'});
  await desktop.waitForFunction(()=>document.getElementById('research-count').textContent.includes('68,521'));
  await desktop.screenshot({path:path.join(dir,'desktop-default.png'),fullPage:false});
  await desktop.close();
  assert.deepEqual(errors,[]);
  const broken=await page.locator('a').evaluateAll(a=>a.filter(x=>!/^https?:/.test(x.href)).map(x=>x.href));assert.deepEqual(broken,[]);
  console.log('PASS regions, 43 municipalities, S filter, search, empty state, pagination through ALL 68521 records, mobile overflow, JS errors');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
